spam and non spam algorithm

naive bayes is used for classification algorithm(binary) much like a logistic regression


Problem Statement : Given X is an email object you have to predict that X is a spam email or not 


we have to find the posterior probability

p(a/b)=p(a)*p(b/a)/p(b)

p(a) --> likelyhood 
p(a/b) --> probability of a if b is already occured
p(b/a) --> probability of b if a is already occured
p(b)--> 

P(y=1/x)= for i --> n (pxi/y=1).p(y=1)

p(y=0/x)= for i --> n p(xi/y=0).p(y=0)

Naive Bayes Algorithm Scratch

In [412]:
import pandas as pd
import numpy as np

In [413]:
golf=pd.read_csv("golf.csv")
golf.head()

Outlook Temperature Humidity  Windy Play
0     sunny         hot     high  False   no
1     sunny         hot     high   True   no
2  overcast         hot     high  False  yes
3     rainy        mild     high  False  yes
4     rainy        cool   normal  False  yes

In [414]:
def prior_probab(golf,label):
    total_examples=golf.shape[0]
    class_examples=(golf['Play']==label).sum()

    return class_examples/total_examples



prior probability

In [415]:
prior_probab(golf,"no"), prior_probab(golf,"yes")

(0.35714285714285715, 0.6428571428571429)

creating dict to store the prior probability for y=1 and y=0

In [416]:
PRIOR={

"yes":prior_probab(golf,"yes"),
"no":prior_probab(golf,"no")
}

In [417]:
prior

0.6428571428571429

conditional probability

In [418]:
def cond_probab(golf,feature,feature_value,label):
    filtered_data=golf[golf['Play']==label]
    numerator=np.sum(filtered_data[feature]==feature_value)
    denominator=filtered_data.shape[0]
    return numerator/denominator

In [419]:
cond_probab(golf,'Humidity',"normal",'no')

0.2

In [420]:
features=list(golf.columns)[:-1]
features

cond_prob={}

for label in golf['Play'].unique():
    cond_prob[label]={}
    for feature in features:
        cond_prob[label][feature]={}
        
        feature_values=golf[feature].unique()

        for fea_value in feature_values:
            # print(fea_value,feature_values)
            print(cond_probab(golf,feature,fea_value,label))
            prob=round(cond_probab(golf,feature,fea_value,label),2)
            cond_prob[label][feature][fea_value]=prob
            print(label,feature,fea_value,prob)




0.6
no Outlook sunny 0.6
0.0
no Outlook overcast 0.0
0.4
no Outlook rainy 0.4
0.4
no Temperature hot 0.4
0.4
no Temperature mild 0.4
0.2
no Temperature cool 0.2
0.8
no Humidity high 0.8
0.2
no Humidity normal 0.2
0.4
no Windy False 0.4
0.6
no Windy True 0.6
0.2222222222222222
yes Outlook sunny 0.22
0.4444444444444444
yes Outlook overcast 0.44
0.3333333333333333
yes Outlook rainy 0.33
0.2222222222222222
yes Temperature hot 0.22
0.4444444444444444
yes Temperature mild 0.44
0.3333333333333333
yes Temperature cool 0.33
0.3333333333333333
yes Humidity high 0.33
0.6666666666666666
yes Humidity normal 0.67
0.6666666666666666
yes Windy False 0.67
0.3333333333333333
yes Windy True 0.33


In [421]:
cond_prob

{'no': {'Outlook': {'sunny': 0.6, 'overcast': 0.0, 'rainy': 0.4},
  'Temperature': {'hot': 0.4, 'mild': 0.4, 'cool': 0.2},
  'Humidity': {'high': 0.8, 'normal': 0.2},
  'Windy': {False: 0.4, True: 0.6}},
 'yes': {'Outlook': {'sunny': 0.22, 'overcast': 0.44, 'rainy': 0.33},
  'Temperature': {'hot': 0.22, 'mild': 0.44, 'cool': 0.33},
  'Humidity': {'high': 0.33, 'normal': 0.67},
  'Windy': {False: 0.67, True: 0.33}}}

In [422]:
X_test=['sunny','hot','normal',False]

In [423]:
for label in golf['Play'].unique():
    prior=PRIOR[label]
    likelihood=1.0

    for i in range (len(features)):
        feature=features[i]
        fea_value=X_test[i]
        
        likelihood*=cond_prob[label][feature][fea_value]
        

    post=likelihood*prior

    print(label,post) 


no 0.006857142857142858
yes 0.013967202857142858


In [424]:
0.006/(0.006+0.0013)

0.821917808219178

Naive bayes implementation using sklearn

In [425]:
golf=pd.read_csv('golf.csv')

In [426]:
golf.head()

Outlook Temperature Humidity  Windy Play
0     sunny         hot     high  False   no
1     sunny         hot     high   True   no
2  overcast         hot     high  False  yes
3     rainy        mild     high  False  yes
4     rainy        cool   normal  False  yes

need to encode the values from the dataset

In [427]:
from sklearn.preprocessing import LabelEncoder

In [428]:
le1=LabelEncoder()
golf['Outlook']=le1.fit_transform(golf['Outlook'])

In [429]:
le2=LabelEncoder()
golf['Temperature']=le2.fit_transform(golf['Temperature'])

In [430]:
le3=LabelEncoder()
golf['Humidity']=le3.fit_transform(golf['Humidity'])

In [431]:
le4=LabelEncoder()
golf['Windy']=le3.fit_transform(golf['Windy'])

In [432]:
golf

Outlook  Temperature  Humidity  Windy Play
0         2            1         0      0   no
1         2            1         0      1   no
2         0            1         0      0  yes
3         1            2         0      0  yes
4         1            0         1      0  yes
5         1            0         1      1   no
6         0            0         1      1  yes
7         2            2         0      0   no
8         2            0         1      0  yes
9         1            2         1      0  yes
10        2            2         1      1  yes
11        0            2         0      1  yes
12        0            1         1      0  yes
13        1            2         0      1   no

In [433]:
le5=LabelEncoder()
golf['Play']=le5.fit_transform(golf['Play'])

In [434]:
golf

Outlook  Temperature  Humidity  Windy  Play
0         2            1         0      0     0
1         2            1         0      1     0
2         0            1         0      0     1
3         1            2         0      0     1
4         1            0         1      0     1
5         1            0         1      1     0
6         0            0         1      1     1
7         2            2         0      0     0
8         2            0         1      0     1
9         1            2         1      0     1
10        2            2         1      1     1
11        0            2         0      1     1
12        0            1         1      0     1
13        1            2         0      1     0

importing the model from sklearn

In [435]:
from sklearn.naive_bayes import CategoricalNB

In [436]:
model=CategoricalNB()

In [437]:
X=golf.iloc[:,:-1]
y=golf.iloc[:,-1]

In [438]:
model.fit(X,y)

CategoricalNB()

getting the testing data and encoding it 


In [439]:
X_train=['Sunny','hot','normal','no']

In [440]:
le1.transform(['sunny'])

array([2])

In [441]:
le2.transform(['hot'])

array([1])

In [442]:
le3.transform(['normal'])

array([1])

In [443]:
le5.transform(['no'])

array([0])

In [444]:
X_test=np.array([[2,1,1,0]])

In [445]:
X_test

array([[2, 1, 1, 0]])

In [447]:
predict=model.predict(X_test)

/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


calculating the probability for the test data

In [449]:
model.predict_proba(X_test)

/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


array([[0.33508723, 0.66491277]])